# Generated by Django 5.0.6 on 2024-11-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soCCCD', models.IntegerField(unique=True)),
                ('hoTenBacSi', models.CharField(max_length=50)),
                ('tuoi', models.IntegerField()),
                ('gioiTinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=5)),
                ('soDienThoai', models.IntegerField()),
                ('diaChi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soCCCD', models.IntegerField(blank=True, null=True, unique=True)),
                ('maBaoHiemYTe', models.IntegerField(blank=True, null=True, unique=True)),
                ('hoTenBenhNhan', models.CharField(max_length=50)),
                ('tuoi', models.IntegerField()),
                ('gioiTinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=5)),
                ('soDienThoai', models.IntegerField()),
                ('diaChi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HoSoBenhAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoiGianKham', models.DateTimeField(auto_created=True)),
                ('trieuChung', models.CharField(max_length=255)),
                ('chuanDoan', models.CharField(max_length=255)),
                ('dieuTri', models.CharField(max_length=255)),
                ('benhNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.benhnhan')),
            ],
        ),
    ]
