# Generated by Django 5.0.6 on 2024-11-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_manager_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='fullname',
            new_name='fullName',
        ),
    ]
